name: Check_Ubuntu compilation C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ./run.sh
      run: ./run.sh
           cat diff.txt
           uname -m
