# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    vector.yml                                         :+:    :+:             #
#                                                      +:+                     #
#    By: pde-bakk <pde-bakk@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/10/25 13:16:01 by pde-bakk      #+#    #+#                  #
#    Updated: 2020/10/25 13:16:02 by pde-bakk      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

name: Vector - Check Ubuntu & macOS compilation C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  jobuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ./run.sh workflow
      run: |
        echo "Starting to run tests!"
        ./run.sh vector debug

  stevejobs:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: ./run.sh workflow
      run: |
        ./run.sh vector debug
